version: '3.5'
services:
  minecraft:
    build: .
    image: minecraft
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    # volumes:
    #   - ./world:/data
    env_file:
      - .env
      - .env.private
